-- MySQL Script generated by MySQL Workbench
-- 07/02/17 23:02:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blah
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `description` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `hash` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
;


-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tag` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`))
;


-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `site` VARCHAR(255) NULL,
  `tel` VARCHAR(45) NULL,
  `lat` DOUBLE NULL,
  `lng` DOUBLE NULL,
  `location` TEXT NULL,
  PRIMARY KEY (`idaddress`))
;


-- -----------------------------------------------------
-- Table `place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `place` (
  `idplace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `fk_address` INT NULL,
  `picture` VARCHAR(255) NULL,
  `likes` INT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idplace`),
  INDEX `fk_address_idx` (`fk_address` ASC),
  CONSTRAINT `fk_address`
    FOREIGN KEY (`fk_address`)
    REFERENCES `address` (`idaddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route` (
  `id_route` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NULL,
  `description` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `portrayde_date` DATETIME NULL,
  `rate` FLOAT NULL,
  `main_picture` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id_route`),
  INDEX `fk_user_idx` (`fk_user` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`fk_user`)
    REFERENCES `user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `route_pics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route_pics` (
  `id_route_pics` INT NOT NULL AUTO_INCREMENT,
  `fk_route` INT NULL,
  `photo` VARCHAR(255) NULL,
  `label` VARCHAR(255) NULL,
  PRIMARY KEY (`id_route_pics`),
  INDEX `fk_route_idx` (`fk_route` ASC),
  CONSTRAINT `fk_route`
    FOREIGN KEY (`fk_route`)
    REFERENCES `route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `route_evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route_evaluation` (
  `id_route_evaluation` INT NOT NULL AUTO_INCREMENT,
  `fk_route` INT NULL,
  `comments` TEXT NULL,
  `star` INT NULL,
  `spend` DECIMAL NULL,
  `fk_user` INT NULL,
  `date_time` DATETIME NULL,
  PRIMARY KEY (`id_route_evaluation`))
;


-- -----------------------------------------------------
-- Table `interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactions` (
  `idinteractions` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idinteractions`))
;


-- -----------------------------------------------------
-- Table `route_interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route_interactions` (
  `idroute_interactions` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_route` INT NOT NULL,
  `id_interaction` INT NOT NULL,
  PRIMARY KEY (`idroute_interactions`),
  INDEX `interaction_id_idx` (`id_interaction` ASC),
  INDEX `user_id_idx` (`id_user` ASC),
  INDEX `route_id_idx` (`id_route` ASC),
  CONSTRAINT `interaction_id`
    FOREIGN KEY (`id_interaction`)
    REFERENCES `interactions` (`idinteractions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`id_user`)
    REFERENCES `user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `route_id`
    FOREIGN KEY (`id_route`)
    REFERENCES `route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `route__tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route__tag` (
  `id_route_tag` INT NOT NULL,
  `id_route` INT NOT NULL,
  `id_tag` INT NOT NULL,
  `str_tags` TEXT NULL,
  PRIMARY KEY (`id_route_tag`),
  INDEX `fk_route__tag_tag1_idx` (`id_tag` ASC),
  INDEX `fk_route__tag_route_idx` (`id_route` ASC),
  CONSTRAINT `fk_route__tag_tag1`
    FOREIGN KEY (`id_tag`)
    REFERENCES `tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route__tag_route`
    FOREIGN KEY (`id_route`)
    REFERENCES `route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `trip__place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip__place` (
  `idtrip__place` INT NOT NULL AUTO_INCREMENT,
  `fk_route` INT NULL,
  `fk_place` INT NULL,
  PRIMARY KEY (`idtrip__place`))
;


-- -----------------------------------------------------
-- Placeholder table for view `short_trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `short_trip` (`id_trip` INT, `rate` INT, `title` INT, `short_route` INT, `create_time` INT, `name_user` INT, `url_user_picture` INT);

-- -----------------------------------------------------
-- Placeholder table for view `full_trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full_trip` (`id_trip` INT, `rate` INT, `title` INT, `short_route` INT, `create_time` INT, `tags` INT, `name_user` INT, `url_user_picture` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trip_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_images` (`url` INT, `label` INT, `id_trip` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trip_places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_places` (`id_place` INT, `name_place` INT, `url_picture` INT, `likes` INT, `description` INT, `id_trip` INT, `lat` INT, `lng` INT, `location` INT, `address` INT, `site` INT, `tel` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trip_evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trip_evaluations` (`id_trip` INT, `comments` INT, `date_time` INT, `name_user` INT, `url_user_picture` INT);

-- -----------------------------------------------------
-- Placeholder table for view `show_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_place` (`id_place` INT, `name_place` INT, `url_picture` INT, `likes` INT, `description` INT, `tel` INT, `site` INT, `address` INT);

-- -----------------------------------------------------
-- View `short_trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `short_trip`;
CREATE  OR REPLACE VIEW `short_trip` AS
select  
	r.id_route as id_trip,
    r.rate as rate,
    r.title as title,
    r.description as short_route,
    r.create_date as create_time,
	u.name as name_user, 
    u.photo as url_user_picture
FROM  route AS r 
INNER JOIN user as u ON u.id_user = r.fk_user;

-- -----------------------------------------------------
-- View `full_trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `full_trip`;
CREATE  OR REPLACE VIEW `full_trip` AS
select  
	r.id_route as id_trip,
    r.rate as rate,
    r.title as title,
    r.description as short_route,
    r.create_date as create_time,
    t.str_tags as tags,
	u.name as name_user, 
    u.photo as url_user_picture
FROM  route AS r 
INNER JOIN user as u ON u.id_user = r.fk_user
INNER JOIN route__tag as t ON r.id_route = t.id_route;

-- -----------------------------------------------------
-- View `trip_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trip_images`;
CREATE  OR REPLACE VIEW `trip_images` AS
SELECT 
rp.photo as url,
rp.label as label,
r.id_route as id_trip
FROM route_pics as rp
INNER JOIN route as r on r.id_route = rp.fk_route;

-- -----------------------------------------------------
-- View `trip_places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trip_places`;
CREATE  OR REPLACE VIEW `trip_places` AS
SELECT
p.idplace as id_place,
p.name as name_place,
p.picture as url_picture,
p.likes as likes,
p.description as description,
r.id_route as id_trip,
a.lat as lat,
a.lng as lng,
a.location as location,
a.street as address,
a.site as site,
a.tel as tel
FROM place as p
INNER JOIN trip__place as tp ON tp.fk_place = p.idplace
INNER JOIN route as r ON tp.fk_route = r.id_route
INNER JOIN address as a ON a.idaddress = p.fk_address;

-- -----------------------------------------------------
-- View `trip_evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trip_evaluations`;
CREATE  OR REPLACE VIEW `trip_evaluations` AS
SELECT
r.id_route as id_trip,
re.comments AS comments,
re.date_time AS date_time,
u.name AS name_user,
u.photo AS url_user_picture
FROM route_evaluation AS re 
INNER JOIN route as r ON re.fk_route = r.id_route
INNER JOIN user as u ON u.id_user = re.fk_user;

-- -----------------------------------------------------
-- View `show_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `show_place`;
CREATE  OR REPLACE VIEW `show_place` AS
SELECT 
p.idplace as id_place,
p.name as name_place,
p.picture as url_picture,
p.likes as likes,
p.name as description,
a.tel as tel,
a.site as site,
a.street as address
FROM place as p
INNER JOIN address as a ON p.fk_address = a.idaddress;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
