-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 12:54:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blah
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blah` DEFAULT CHARACTER SET utf8 ;
USE `blah` ;

-- -----------------------------------------------------
-- Table `blah`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `description` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`tag` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`route` (
  `id_route` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NULL,
  `fk_tag` INT NULL,
  `description` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  `portrayde_date` DATETIME NULL,
  PRIMARY KEY (`id_route`),
  INDEX `fk_user_idx` (`fk_user` ASC),
  INDEX `fk_tag_idx` (`fk_tag` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`fk_user`)
    REFERENCES `blah`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag`
    FOREIGN KEY (`fk_tag`)
    REFERENCES `blah`.`tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`place` (
  `idplace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `fk_address` INT NULL,
  `fk_route` INT NULL,
  PRIMARY KEY (`idplace`),
  INDEX `fk_address_idx` (`fk_address` ASC),
  INDEX `fk_route_idx` (`fk_route` ASC),
  CONSTRAINT `fk_address`
    FOREIGN KEY (`fk_address`)
    REFERENCES `blah`.`address` (`idaddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route`
    FOREIGN KEY (`fk_route`)
    REFERENCES `blah`.`route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`place_evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`place_evaluation` (
  `id_evaluation` INT NOT NULL AUTO_INCREMENT,
  `fk_place` INT NOT NULL,
  `coment` VARCHAR(144) NULL,
  `star` INT NULL,
  `spend` DECIMAL NULL,
  `fk_user` INT NULL,
  PRIMARY KEY (`id_evaluation`),
  INDEX `fk_places_idx` (`fk_place` ASC),
  INDEX `fk_user_idx` (`fk_user` ASC),
  CONSTRAINT `fk_places`
    FOREIGN KEY (`fk_place`)
    REFERENCES `blah`.`place` (`idplace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`fk_user`)
    REFERENCES `blah`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`route_pics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`route_pics` (
  `id_route_pics` INT NOT NULL AUTO_INCREMENT,
  `fk_route` INT NULL,
  `photo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_route_pics`),
  INDEX `fk_route_idx` (`fk_route` ASC),
  CONSTRAINT `fk_route`
    FOREIGN KEY (`fk_route`)
    REFERENCES `blah`.`route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blah`.`route_evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blah`.`route_evaluation` (
  `id_route_evaluation` INT NOT NULL AUTO_INCREMENT,
  `fk_route` INT NULL,
  `comment` VARCHAR(144) NULL,
  `star` INT NULL,
  `spend` DECIMAL NULL,
  `fk_user` INT NULL,
  PRIMARY KEY (`id_route_evaluation`),
  INDEX `fk_user_idx` (`fk_user` ASC),
  INDEX `fk_route_idx` (`fk_route` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`fk_user`)
    REFERENCES `blah`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route`
    FOREIGN KEY (`fk_route`)
    REFERENCES `blah`.`route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
